name: "Tests"

on:
  push:
    branches:
      - stable
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.3, 8.4, 8.5]
        laravel-version: ["11.*", "12.*", "13.*"]
        include:
          - php-version: 8.5
            laravel-version: "13.*"
            coverage: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.laravel-version }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.laravel-version }}-${{ matrix.php-version }}-composer-

      - name: Lock laravel/framework version
        run: composer require laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Install dependencies
        run: composer update --no-interaction

      - name: Run test suites
        run: composer run-script ${{ matrix.coverage && 'test-with-coverage' || 'test' }}

      - name: Coveralls
        if: matrix.coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/php-coveralls -v --coverage_clover=build/logs/clover.xml
