name: "Tests"

# Triggers the workflow on push or pull request events
on: 
  push:
    branches:
      - stable
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.2, 8.3, 8.4]
        laravel-version:
          [
            "9.*", # Test Laravel 9
            "10.*", # Test Laravel 10
            "11.*", # Test  Laravel 11
          ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.laravel-version }}-${{matrix.php-version}}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.laravel-version }}-${{matrix.php-version}}-composer-

      - name: Lock laravel/framework version
        env:
          LARAVEL_VERSION: ${{ matrix.laravel-version }}
        run: composer require laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Vendor update
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --prefer-source --no-interaction

      - name: Run test suites
        run: composer run-script test

      - name: Coveralls
        if: matrix.laravel-version != '9.*'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/php-coveralls -v --coverage_clover=build/logs/clover.xml