name: "Tests"

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 6.x
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.3, 8.4, 8.5]
        laravel-version: ["12.*", "13.*"]
        include:
          - php-version: 8.5
            laravel-version: "13.*"
            coverage: true

    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}

      - name: Lock laravel/framework version
        run: composer require laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Install dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1
        with:
          dependency-versions: highest
          custom-cache-suffix: ${{ matrix.php-version }}-${{ matrix.laravel-version }}

      - name: Run test suites
        run: composer run-script ${{ matrix.coverage && 'test-with-coverage' || 'test' }}

      - name: Upload coverage to Coveralls
        if: matrix.coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          file: build/logs/clover.xml
